### ISSUE TITLE
[BUG] Token refresh is not thread-safe

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#31]
The authentication token for FDUHole needs to be refreshed periodically, but currently, there's no mechanisms to prevent multiple requests from trying to refresh the token at the same time. This may lead to occasional 401 errors from some APIs.

This problem can be fixed by adding a readers–writer lock, as described in #12.

**Comment by singularity-s0** [comment]
How about we just make everything serial for now? We can optimize the implementation later.

**Comment by singularity-s0** [comment]
Is there any structured way of making things serial?

**Comment by singularity-s0** [comment]
> I believe `httpMaximumConnectionsPerHost` of `URLSessionConfiguration` is suitable for this. 

As I have said, being single-threaded doesn't mean there are no longer any concurrency problems. Consider the following scenario:

A and B wants to obtain tickets from UIS. A and B start requests with the same stored cookie. Both requests enter a queue. A's request goes first and finds that the cookie has expired. A starts another request to re-logins to UIS. However, B's request will start before A's re-login request because it's at the front of the queue. So B will send another useless request only to find out (again) its token has expired. And B also starts another request to re-login to UIS.

Although only one request is sent at a time, the total number of requests remain the same. The concurrency problem still remains.

**Comment by w568w** [comment]
By the way, what is wrong with a read-write lock? 

I were thinking the mechanism I had proposed before was both correct and easy-to-implement...?

**Comment by singularity-s0** [comment]
> I think you are off-topic. This issue has nothing to do with UIS service. 

This is only an example. The same thing happens with JWT refresh.

**Comment by singularity-s0** [comment]
> And read-write lock itself is also easy to implement with either a semaphore or a mutex.

The problem is that Swift has nearly none of the async concurrency primitives. We have to implement them ourselves.

**Comment by singularity-s0** [comment]
[This article](https://www.kodeco.com/28540615-grand-central-dispatch-tutorial-for-swift-5-part-1-2/page/3) claims we could use [Dispatch Barriers](https://developer.apple.com/documentation/dispatch/dispatch_barrier) to deal with our readers-writers problem. Perhaps we should take a look.

**Comment by w568w** [comment]
> Swift has nearly none of the async concurrency primitives

😿
