### ISSUE TITLE
All local cache should be cleared after user log out

### ISSUE THREAD

**Issue by fsy2001** [DanXi-Dev/DanXi-swift#49]
There are some local cache used by campus services, including course table, user profile, etc. These caches should be cleared when user log out to prevent security issue and data inconsistency.

**Comment by singularity-s0** [comment]
## AppStorage
`@AppStorage` uses `UserDefault` as backend. For data stored using `@AppStorage`, we should prefix string keys with relevant service. E.g., `@AppStorage("sensitive-content")` should be turned into `@AppStorage("dx-sensitive-content")` so that when user logout of DanXi account, we can use the following code to clean up all DanXi data

```swift
func resetDXDefaults() {
    let defaults = UserDefaults.standard
    let dictionary = defaults.dictionaryRepresentation()
    dictionary.keys.forEach { key in
        if key.hasPrefix("dx") {
            defaults.removeObject(forKey: key)
        }
    }
}
```

## Disk
For data stored using `Disk`, we should put them in subdirectories for UIS services and DanXi services respectively. E.g., calendar data should be stored under `$(base)/uis/calendar.json`, so that when user logout of UIS, we can simply remove the `$(base)/uis/` directory
